server:
  port: 8080
spring:
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka